# basic settings
theme: minima
markdown: GFM
highlighter: rouge
exclude:
  - .editorconfig
  - Gemfile
  - Gemfile.lock
  - Makefile

# theme settings
url: &page bluebrown.github.io
title: *page
description: >-
  Nico Braun's Personal Website.
  A blog about programming, technology, and life.

author: &author Nico Braun
email: rainbowstack@gmail.com
github_username: bluebrown
linkedin_username: nico-braun
twitter_username: codingsafari

show_excerpts: true
google_analytics: ~

# default
defaults:
  - scope:
      path: ""
      type: posts
    values:
      author: *author
      permalink: /:categories/:title

# plugin settings
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

sass:
  style: compressed
